### ISSUE TITLE
Database connection failed due to 1045 (28000)

### ISSUE THREAD

**Issue by rezabekf** [aws-samples/amazon-rds-proxy-multitenant-load-test#14]
The environment variable [here](https://github.com/aws-samples/amazon-rds-proxy-multitenant-load-test/blob/e9ad62f2ac6e4cdfa830c4d106f35cef941ecb25/cfn/access-function.template#L55) Is causing the issue and 100% of connection is getting dropped. The logs show error
```
Database connection failed due to 1045 (28000): Access denied for user 'user117'@'%' (using password: NO)
```
The working solutions is to remove `${DbClusterResourceId}` and replace it with `*` which essentially give access to any cluster/database instance in the account. 

The `Access denied` error only appears when connecting to database with Proxy in front of it. The No Proxy cluster access is fine and working as expected.

**Comment by samsanders23** [comment]
![Screenshot 2021-04-30 at 14 57 40](https://user-images.githubusercontent.com/40782383/116722632-8e464f00-a9d6-11eb-9046-57f82bce8913.png)
The issue can be fixed by replacing the `${DbClusterResourceId}` with the trailing of characters of the proxy arn, after `db-proxy: ` as shown in the diagram
